apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: post-stg-sanity-run-20
  namespace: experimental-pipeline
spec:
  taskRef:
    name: post-stg-sanity-19
  inputs:
    resources:
      - name: myapp-image
        resourceRef:
          name: myapp-resource
