apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: apply-stg-1
  namespace: experimental-pipeline
spec:
  inputs:
    resources:
      - name: myapp-image
        type: image
    params:
      - name: version
        type: string
        description: the app release version
  steps:
    - name: apply
      image: gcr.io/yuwenma-gke-playground/k8s-appctl:v5.0.0-betaNoPRReview
      command: ["/bin/bash"]
      args: ['-c', 'gcloud auth activate-service-account kalm-test@yuwenma-gke-playground.iam.gserviceaccount.com  --key-file=/gcloud-serviceaccount-key.json && cd /myapp && gcloud config list && appctl apply stg --from-tag $(inputs.params.version) && kubectl get releasetrack -n myapp-stg']
