apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: prepare-stg-1
  namespace: experimental-pipeline
spec:
  inputs:
    resources:
      - name: myapp-image
        type: image
    params:
      - name: version
        type: string
        description: the app release version
  steps:
    - name: prepare
      image: gcr.io/yuwenma-gke-playground/k8s-appctl:v5.0.0-betaNoPRReview
      command: ["/bin/bash"]
      args: ['-c', 'git config --global user.email "yuwenma@google.com"  &&  git config --global user.name "Yuwen Robot" && cd /myapp && appctl prepare stg --from-tag $(inputs.params.version)']
