apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: post-prod-sanity-1
  namespace: experimental-pipeline
spec:
  steps:
    - name: wait
      image: ubuntu
      command:
      - /bin/bash
      args:
      - -c
      - |
        sleep 10
    - name: run-kubectl
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl get releasetrack -n myapp-prod"]

      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "get"
        - "releasetrack"
        - "-n myapp-prod"
  steps:
    - name: check
      image: gcr.io/yuwenma-gke-playground/k8s-appctl:v5.0.0-betaNoPRReview
      command: ["/bin/bash"]
      args: ['-c', 'echo "Prod release Succeed!!!"']
