apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: pipelinerun-qa
  namespace: experimental-pipeline
spec:
  pipelineRef:
    name: pipeline-qa
  resources:
    - name: resource-for-pipeline
      resourceRef:
        name: pipeline-app-resource
