apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: pipeline-app-resource
  namespace: experimental-pipeline
spec:
  type: git
  params:
    - name: url
      value: https://github.com/yuwenma/app-pipeline-demo.git
