apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline-dev
  namespace: experimental-pipeline
spec:
  tasks:
    - name: dev-prep
      taskRef:
        name: prepare-dev-1
      resources:
        inputs:
          - name: pipeline-app-image
            resource: resource-for-pipeline
      params:
        - name: version
          value: #IMG_VERSION#
    - name: dev-apply
      taskRef:
        name: apply-dev-1
      resources:
        inputs:
          - name: pipeline-app-image
            resource: resource-for-pipeline
      params:
        - name: version
          value: #IMG_VERSION#
      runAfter:
        - dev-prep
    - name: post-dev-check
      taskRef:
        name: post-dev-sanity-1
      runAfter:
        - dev-apply
  resources:
    - name: resource-for-pipeline
      type: image
